### ISSUE TITLE
Convert model.h5 to tflite

### ISSUE THREAD

**Issue by QendKrasniqi** [breizhn/DTLN#1]
I'm trying to convert the provided pretrained model to tflite:

`
converter = tf.lite.TocoConverter.from_keras_model_file("./model.h5")
tflite_model = converter.convert()
open(os.path.join(".", "model.tflite"), 'wb').write(tflite_model)
`

And I get the following error:

`
ValueError: No model found in config file.
`

Full error message:

`
Traceback (most recent call last):
  File "/home/qendrim/solaborate/repos/solaborate/Solaborate.ML.KPP/src/s4_export_to_tflite.py", line 18, in <module>
    converter = tf.lite.TocoConverter.from_keras_model_file("./model.h5")
  File "/home/qendrim/anaconda3/envs/solaborate-ml/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/qendrim/anaconda3/envs/solaborate-ml/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1002, in from_keras_model_file
    input_shapes, output_arrays)
  File "/home/qendrim/anaconda3/envs/solaborate-ml/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 747, in from_keras_model_file
    keras_model = _keras.models.load_model(model_file, custom_objects)
  File "/home/qendrim/anaconda3/envs/solaborate-ml/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/qendrim/anaconda3/envs/solaborate-ml/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 209, in load_model_from_hdf5
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.
`

python: 3.7
tensorflow: 1.4 

What can I do to convert this model to tflite?

**Comment by breizhn** [comment]
**The model can not be converted to TF lite  yet.** 

One of the reasons is that TF lite's `exp()` does not support complex64 so it can not be converted and LSTMs are still a tricky thing in TensorFlow Lite. The TensorFlow team is working on support for standard TensorFlow operations, but this is still under development and there isn't a python runtime for this yet. See this [guide](https://www.tensorflow.org/lite/guide/ops_select) for more informations.

And actually you tried to convert a .h5 weight file  to a tf lite model. The .h5 file in this repository contains just the the weights and no model description. You have to build the model first to convert it. See the `run_evaluation.py` for building the model and loading the weights.

But if you are looking for fast inference, maybe use the SavedModel format. This one is already running fast and is portable.

**Comment by breizhn** [comment]
Tf lite conversion is no added.
