### ISSUE TITLE
error on run  noisyspeech_synthesizer_multiprocessing.py

### ISSUE THREAD

**Issue by dttlgotv** [breizhn/DTLN#22]
I clone your dns-challage fork, and run python noisyspeech_synthesizer_multiprocessing.py. But error can be seen below:

WARNING: Audio type not supported
Generating file #59032
WARNING: Audio type not supported
Generating file #59220
WARNING: Audio type not supported
Generating file #59408
WARNING: Audio type not supported
Generating file #59596
WARNING: Audio type not supported
Generating file #59784
WARNING: Audio type not supported
Generating file #59972
WARNING: Audio type not supported
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/.conda/envs/train_env/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/.conda/envs/train_env/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "noisyspeech_synthesizer_multiprocessing.py", line 156, in main_gen
    gen_audio(True, params, filenum)
  File "noisyspeech_synthesizer_multiprocessing.py", line 124, in gen_audio
    build_audio(is_clean, params, filenum, audio_samples_length)
  File "noisyspeech_synthesizer_multiprocessing.py", line 75, in build_audio
    input_audio, fs_input = audioread(source_files[idx])
  File "/data1/dtln/fork-dns-challenge/audiolib.py", line 46, in audioread
    if len(audio.shape) == 1:  # mono
AttributeError: 'NoneType' object has no attribute 'shape'
"""

**Comment by breizhn** [comment]
Did you use git-lfs as described in the README? Does the .wav files have content?

**Comment by dttlgotv** [comment]
> 
> 
> Did you use git-lfs as described in the README? Does the .wav files have content?

You are right. I have to reinstal lfs again.
